### ISSUE TITLE
无法渲染的问题

### ISSUE THREAD

**Issue by Merofine** [79E/hexo-theme-quiet#13]
我按照README的流程走了下来，但是当我点击后categories时，网页成功跳转，但是却无法渲染，如下图
![image](https://user-images.githubusercontent.com/33657760/146513957-d0905de3-1d3d-4338-b3d7-6f5aee155905.png)

期待大佬的回复。

**Comment by 79W** [comment]
> 我按照README的流程走了下来，但是当我点击后categories时，网页成功跳转，但是却无法渲染，如下图 ![image](https://user-images.githubusercontent.com/33657760/146513957-d0905de3-1d3d-4338-b3d7-6f5aee155905.png)
> 
> 期待大佬的回复。

收到 可以留下你的邮箱吗？ 这里可能是 没有进行解析md文件 很想知道你用的hexo的版本等信息～

**Comment by Merofine** [comment]
> 
感觉回复，我的邮箱是 704783475@qq.co,

![image](https://user-images.githubusercontent.com/33657760/146738672-4c52c534-c067-4a45-a5ce-3d5356e1d02a.png)

**Comment by Merofine** [comment]
你的博客弄得很好看，希望自己也可以弄一个。0，0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月19日(星期天) 晚上6:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [79E/hexo-theme-quiet] 无法渲染的问题 (Issue #13)





  
我按照README的流程走了下来，但是当我点击后categories时，网页成功跳转，但是却无法渲染，如下图 
 
期待大佬的回复。
  
收到 可以留下你的邮箱吗？ 这里可能是 没有进行解析md文件 很想知道你用的hexo的版本等信息～
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 79W** [comment]
> 你的博客弄得很好看，希望自己也可以弄一个。0，0
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月19日(星期天) 晚上6:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [79E/hexo-theme-quiet] 无法渲染的问题 (Issue #13) 我按照README的流程走了下来，但是当我点击后categories时，网页成功跳转，但是却无法渲染，如下图 期待大佬的回复。 收到 可以留下你的邮箱吗？ 这里可能是 没有进行解析md文件 很想知道你用的hexo的版本等信息～ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我给你的邮箱发送了一个我已经搭建好的项目你可以参看下看看 你的邮箱可以在发我一下吗 ？ 我总感觉你上面的邮箱是错误的
