### ISSUE TITLE
这是哪一步出错了？

### ISSUE THREAD

**Issue by kuektic** [79E/hexo-theme-quiet#31]
![image](https://user-images.githubusercontent.com/95989221/219829105-f02690b8-3328-4467-8ef8-1202a47a2f1c.png)

**Comment by 79W** [comment]
这看着像你没有安装 less 插件 

css 样式没有加载出来

本主题使用 less  对 css 进行处理 所以依赖 `hexo-renderer-less `安装后重新编译即可

`npm i hexo-renderer-less`
